title: Blandine JATSA NGUETSE # your name (or website title) here
logo: "/images/profilsinkedIn.PNG?raw=true" # your photo (or logo ) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Je travaille au quotidien dans l'extraction, le traitement et l'analyse pointue des données afin de
  générer de la connaissance. Mes atouts pour réussir: la curiosité, la rigueur et l'esprit de synthèse. 
  <br><br>
  Mon moteur de carrière est de valoriser l'ensemble des données recueillies en masse (big data) pour réaliser les 
  nombreux reporting nécessaires à différents services et acteurs grâce a une compréhension éclairée des enjeux 
  métier, un accompagnement adapté auclient et une capacité de travail en équipe dans un environnement dynamique. 
  <br><br>
  <a href="https://www.linkedin.com/in/blandine-jatsa-nguetse-ingenieur-data-scientist-connaissance-client-cdi/"> Mon Profile LinkedIn </a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
